### ISSUE TITLE
Share OIDC handling

### ISSUE THREAD

**Issue by androa** [navikt/dagpenger-joark-mottak#6]
Acquiring a OIDC token is something we'll end up doing in almost every service. We should find a mechanism for reusing it across services.

I'm thinking either putting into navikt/dagpenger-streams or create a separate library for it. But boooo for libraries :(

https://github.com/navikt/dagpenger-joark-mottak/blob/fe7ea1c94df511b8cd350476c674c1bacecdbb44/src/main/kotlin/no/nav/dagpenger/joark/mottak/StsOidcClient.kt#L9

**Comment by geiralund** [comment]
+1 for putting it in navikt/dagpenger-streams .
